### ISSUE TITLE
Support express checkout

### ISSUE THREAD

**Issue by sjelfull** [superbigco/craft-vipps#1]
## Todos

- [x] Figure out why callbacks isn't being fired
- [x] Make fallback page configurable
- [ ] Add template variable to get order status
- [ ] Widget that checks status at interval?
- [x] Capture
- [x] Refund
- [x] Create transaction

## Open questions

- Should this create a new cart for that item, or keep current items if there is any and add to it? Should probably be a setting.
- How to handle fallback page?
