### ISSUE TITLE
Shipping details

### ISSUE THREAD

**Issue by sjelfull** [superbigco/craft-vipps#2]
## Todos

- [x] Use order details
- [x] Get shipping details from order
- [x] Return free shipping line if nothing

## Open questions

- What is the shipping id? The handle in Craft?
