### ISSUE TITLE
Regular checkout

### ISSUE THREAD

**Issue by sjelfull** [superbigco/craft-vipps#3]
## Todos

- [x] Make fallback page configurable
- [ ] Add template variable to get order status
- [ ] Widget that checks status at interval?
- [x] Capture
- [x] Refund
- [x] Create transaction

## Open questions

- See #1
