### ISSUE TITLE
Event log

### ISSUE THREAD

**Issue by sjelfull** [superbigco/craft-vipps#4]
## Todos

- [ ] Log events
- [ ] Add section
- [ ] Figure out flexible way to handle all types of events
- [ ] Add exception handle
- [ ] Error model
- [ ] Display similar to Queue Manager

**Comment by sjelfull** [comment]
Log in Transactions list is probably good enough.
