### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sjelfull** [superbigco/craft-vipps#5]
## Todos

- [ ] Getting started
- [ ] Installation
- [ ] How to get credentials
- [ ] How to setup fallback page
- [ ] Overview
- [ ] How to debug problems
